OpenRakis/Spice86

src/Spice86/Emulator/InterruptHandlers/Dos/DosInt21Handler.cs
with values in master the game which I reverse just returns an error.
I pick the values from dosbox.
=> int21: return free space as dosbox does

src/Spice86.Core/Emulator/CPU/CPU.cs, src/Spice86.Core/Emulator/Callback/IndexBasedDispatcher.cs, src/Spice86.Core/Emulator/Devices/Video/VgaCard.cs, src/Spice86.Core/Emulator/InterruptHandlers/Input/Keyboard/BiosKeyboardBuffer.cs, src/Spice86.Core/Emulator/InterruptHandlers/Input/Keyboard/BiosKeyboardInt9Handler.cs, src/Spice86.Core/Emulator/InterruptHandlers/Input/Keyboard/KeyboardInt16Handler.cs, src/Spice86.Core/Emulator/LoadableFile/Dos/Com/ComLoader.cs, src/Spice86.Core/Emulator/LoadableFile/Dos/Exe/ExeLoader.cs, src/Spice86.Core/Emulator/ReverseEngineer/CSharpOverrideHelper.cs, src/Spice86.Core/Emulator/VM/Machine.cs, src/Spice86.Shared/Interfaces/IKeyScanCodeConverter.cs
Fixes #187 
Tested:
LOGO (emulated)
LOGO (overriden)
Dune (intro, keyboard driven cursor movements)
This totally breaks Prince of Persia (flames, swords, movements), so this is only a draft.
=> Fix keyboard interrupt handlers not being able to get keyboard interrupts nor the keyboard buffer

src/Spice86.Core/Emulator/Callback/Callback.cs, src/Spice86.Core/Emulator/Callback/CallbackHandler.cs, src/Spice86.Core/Emulator/Callback/ICallback.cs, src/Spice86.Core/Emulator/InterruptHandlers/InterruptHandler.cs
Allow device drivers to specify a custom memory location for their interrupt handler stub.
This is useful because by convention the Device Driver Header is installed at offset 0 of the same segment. 
For instance if a program wants to know if an EMS driver is installed it can call INT 21 35 to get the location of the INT 67 handler and then check offset 0xA of the returned segment to get the name of the driver.
See: https://www.lo-tech.co.uk/wiki/LIM_Expanded_Memory_Specification_V4:_Appendix_B
=> Allow specifying a custom interrupt handler location

src/Spice86.Core/Emulator/CPU/Alu.cs
Fix a bug where multiplying two 32 bit numbers with a larger than 32 bit result would truncate to 32 bit.
int * int == int
(long)int * int == long
=> Fix multiplying 32 bit numbers

src/Spice86.Core/Emulator/CPU/InstructionsImpl/Instructions8.cs
According to https://www.felixcloutier.com/x86/sahf
SAHF should only affect SF,ZF,AF,PF and CF.
It was afffecting all the flags.
=> Fix for SAHF affecting more than the 5 flags it should

src/Spice86.Core/Emulator/CPU/CPU.cs, src/Spice86.Core/Emulator/CPU/Exceptions/CpuGeneralProtectionFaultException.cs, src/Spice86.Core/Emulator/CPU/ModRM.cs
This introduces opcode prefix 67 (address size) support, including the decoding of the SIB byte.
This supersedes PR #262 
To keep the PR small I have not yet identified and adjusted all the places where this should be used. I want to get a stable implementation base in first.
=> Initial prefix 67 support

src/Spice86.Core/Emulator/Devices/Video/AeonCard.cs, src/Spice86/ViewModels/VideoBufferViewModel.cs
Make sure we have the right bitmap, memory and presenter. This should avoid a number of illegal memory access crashes.
=> Video memory access crash prevention

src/Spice86.Logging/LoggerService.cs, src/Spice86.Shared/Interfaces/ILoggerService.cs
The `Override()` method only worked if no logger had been created yet. 
The new `WithLogLevel()` method can be used in any class by doing something like
```csharp
_loggerService = loggerService.WithLogLevel(LogEventLevel.Verbose);
```
Very useful when working on a specific class. 
You can set the overall loglevel to Error or Fatal and your class to Verbose or Debug.
=> Allow per-class loglevel overrides.

src/Spice86.Core/Emulator/Devices/Video/AeonCard.cs, src/Spice86.Core/Emulator/Memory/Memory.cs, src/Spice86.Core/Emulator/ReverseEngineer/MemoryBasedDataStructureWithBaseAddressProvider.cs, src/Spice86.Shared/Utils/MemoryUtils.cs
Move the string get/set methods from MemoryUtils and MemoryBasedDataStructureWithBaseAddressProvider classes to Memory manager class.
This provides direct access rather than access to a copy of memory. Also reduces code duplication.
=> Move memory string reading and writing

src/Spice86.Logging/LoggerService.cs
Did a few tests using my current example (Detroit's intro). With this change, and at least in debug, I got from 30 seconds to render up to the first "pixel fade" to only 20, with logging disabled.
With logging enabled more improvements can probably be made (because the hotspots will now be the different `Write`s). The main culprit is `AddProperties` on `GetLogger`, and inside that one the main issue is `String` concatenation while creating the segmented address. I'm sure this can be cached instead of recreated for every single logging event.
=> fix: improve performance by not creating a full logger only to check its enabled status

src/Spice86.Core/Emulator/Devices/Video/Renderer.cs
- Prevent overflow of internal palette.
- Ignore framebuffer overflow (can happen when resolution changes mid-frame)
=> Fix video crashes

src/Spice86.Core/Emulator/Devices/ExternalInput/Pic.cs, src/Spice86.Tests/PicTests.cs
Make Pic and PicTests a bit more easy to understand.
Fix priority and rotation execution order: EOI should be done first and then rotation when they are requested with the same command.
=> Pic round 2

src/Spice86.Core/Emulator/CPU/CPU.cs, src/Spice86.Core/Emulator/CPU/InstructionsImpl/Instructions16.cs, src/Spice86.Core/Emulator/CPU/InstructionsImpl/Instructions16Or32.cs, src/Spice86.Core/Emulator/CPU/InstructionsImpl/Instructions32.cs, src/Spice86.Core/Emulator/CPU/InstructionsImpl/Instructions8.cs, src/Spice86.Core/Emulator/CPU/ModRM.cs, src/Spice86.Core/Emulator/CPU/Stack.cs, src/Spice86.Core/Emulator/Callback/CallbackHandler.cs, src/Spice86.Core/Emulator/Function/FunctionHandler.cs, src/Spice86.Core/Emulator/Gdb/GdbCommandMemoryHandler.cs, src/Spice86.Core/Emulator/InterruptHandlers/Dos/DosInt21Handler.cs, src/Spice86.Core/Emulator/InterruptHandlers/Dos/Ems/ExpandedMemoryManager.cs, src/Spice86.Core/Emulator/InterruptHandlers/Input/Mouse/MouseDriver.cs, src/Spice86.Core/Emulator/InterruptHandlers/VGA/VgaFunctionality.cs, src/Spice86.Core/Emulator/LoadableFile/Dos/Exe/ExeLoader.cs, src/Spice86.Core/Emulator/LoadableFile/Dos/PspGenerator.cs, src/Spice86.Core/Emulator/Memory/IByteReaderWriter.cs, src/Spice86.Core/Emulator/Memory/Indexer/IIndexed.cs, src/Spice86.Core/Emulator/Memory/Indexer/UInt16Indexer.cs, src/Spice86.Core/Emulator/Memory/Indexer/UInt32Indexer.cs, src/Spice86.Core/Emulator/Memory/Indexer/UInt8Indexer.cs, src/Spice86.Core/Emulator/Memory/Memory.cs, src/Spice86.Core/Emulator/ReverseEngineer/CSharpOverrideHelper.cs, src/Spice86.Core/Emulator/ReverseEngineer/MemoryBasedDataStructure.cs, src/Spice86.Tests/MachineTest.cs, src/Spice86.Tests/MainMemoryTest.cs, src/Spice86/Views/PerformanceWindow.axaml
Remove Get / Set methods, use indexers everywhere.
Make indexers depend on IByteReaderWriter instead of Memory.
Create a new IIndexed interface to represent Indexer 8 / 16 / 32 holders.
Motivation: to be able to use a byte array as IIndexed for memory dumps.
=> Rework Memory class

src/Spice86/App.axaml.cs, src/Spice86/ViewModels/MainWindowViewModel.cs, src/Spice86/Views/MainWindow.axaml.cs
Overrides OnOpened and OnClosing in MainWindow.axaml.cs methods instead of using event handlers in App.axaml.cs
Should fix #373 
Test this with Dune on Linux.
=> fix: MainWindow not closing (Avaloniav11)

src/Spice86.Core/Emulator/InterruptHandlers/Input/Keyboard/BiosKeyboardBuffer.cs, src/Spice86.Core/Emulator/InterruptHandlers/Input/Keyboard/BiosKeyboardInt9Handler.cs, src/Spice86.Core/Emulator/InterruptHandlers/Timer/TimerInt8Handler.cs, src/Spice86.Core/Emulator/InterruptHandlers/VGA/VgaFunctionality.cs, src/Spice86.Core/Emulator/Memory/BiosDataArea.cs, src/Spice86.Core/Emulator/Memory/Indexable/ByteArrayBasedIndexable.cs, src/Spice86.Core/Emulator/ReverseEngineer/DataStructure/AbstractMemoryBasedDataStructure.cs, src/Spice86.Core/Emulator/ReverseEngineer/DataStructure/Array/SegmentedAddressArray.cs, src/Spice86.Core/Emulator/ReverseEngineer/DataStructure/Array/UInt16Array.cs, src/Spice86.Core/Emulator/ReverseEngineer/DataStructure/Array/UInt32Array.cs, src/Spice86.Core/Emulator/ReverseEngineer/DataStructure/Array/UInt8Array.cs, src/Spice86.Core/Emulator/VM/Machine.cs, src/Spice86.Tests/MemoryBasedDataStructureTest.cs
Add tests to MemoryBasedDataStructure.
Convert BiosDataArea to Memory Based Structure. 
Complete BiosDataArea with missing fields.
Make BiosKeyboardBuffer use BiosDataArea fields.
=> BDA rework and tests on Memory structs

src/Spice86.Core/Emulator/CPU/Alu.cs, src/Spice86.Core/Emulator/CPU/Alu16.cs, src/Spice86.Core/Emulator/CPU/Alu32.cs, src/Spice86.Core/Emulator/CPU/Alu8.cs, src/Spice86.Core/Emulator/CPU/CPU.cs, src/Spice86.Core/Emulator/CPU/InstructionsImpl/Instructions.cs, src/Spice86.Core/Emulator/CPU/InstructionsImpl/Instructions16.cs, src/Spice86.Core/Emulator/CPU/InstructionsImpl/Instructions16Or32.cs, src/Spice86.Core/Emulator/CPU/InstructionsImpl/Instructions32.cs, src/Spice86.Core/Emulator/CPU/InstructionsImpl/Instructions8.cs, src/Spice86.Core/Emulator/ReverseEngineer/CSharpOverrideHelper.cs, tests/Spice86.Tests/MachineTest.cs
Split the ALU between 8, 16 and 32bits versions with a common class Alu providing common logic and abstract methods.
This is needed to unify instructions behaviour with generic math in cfgcpu.
=> Alu class split between 8, 16 and 32 versions

.github/workflows/autorelease.yml, .github/workflows/codeql.yml, .github/workflows/dotnet.yml, README.md, src/Bufdio.Spice86/Bindings/PortAudio/Structs/PaStreamParameters.cs, src/Bufdio.Spice86/Bufdio.Spice86.csproj, src/Bufdio.Spice86/Engines/IAudioEngine.cs, src/Bufdio.Spice86/Engines/PortAudioEngine.cs, src/Spice86.Core/Spice86.Core.csproj, src/Spice86.Logging/Spice86.Logging.csproj, src/Spice86.Shared/Emulator/Errors/UnrecoverableException.cs, src/Spice86.Shared/Emulator/Memory/SegmentedAddress.cs, src/Spice86.Shared/Spice86.Shared.csproj, src/Spice86/Spice86.csproj, tests/Spice86.Tests/Spice86.Tests.csproj
Upgrades Spcie86 to the latest .NET 8 SDK, released today.
.NET 8 is the new LTS.
6 months from now, .NET 7 will be out of support (EOL).
Test this with your favorite game, if need be. No regressions are expected.
=> Move to .NET 8

src/Spice86.Core/Emulator/Devices/Sound/SoundBlaster.cs, src/Spice86.Core/Emulator/Devices/Sound/Ym7128b/YM7128B.cs, src/Spice86.Core/Emulator/Devices/Timer/Counter.cs, src/Spice86.Core/Emulator/Devices/Timer/Timer.cs, src/Spice86.Core/Emulator/Function/Dump/ExecutionFlowDumper.cs, src/Spice86.Core/Emulator/InterruptHandlers/Bios/BiosEquipmentDeterminationInt11Handler.cs, src/Spice86.Core/Emulator/InterruptHandlers/Bios/SystemBiosInt15Handler.cs, src/Spice86.Core/Emulator/InterruptHandlers/Common/IndexBasedDispatcher/IndexBasedDispatcher.cs, src/Spice86.Core/Emulator/InterruptHandlers/Common/MemoryWriter/MemoryAsmWriter.cs, src/Spice86.Core/Emulator/InterruptHandlers/Dos/DosInt21Handler.cs, src/Spice86.Core/Emulator/InterruptHandlers/Dos/DosInt2fHandler.cs, src/Spice86.Core/Emulator/InterruptHandlers/Input/Mouse/MouseInt33Handler.cs, src/Spice86.Core/Emulator/InterruptHandlers/Timer/TimerInt8Handler.cs, src/Spice86.Core/Emulator/InterruptHandlers/VGA/Records/CharacterPlusAttribute.cs, src/Spice86.Core/Emulator/InterruptHandlers/VGA/Records/VgaMode.cs, src/Spice86.Core/Emulator/InterruptHandlers/VGA/Records/VideoMode.cs, src/Spice86.Core/Emulator/InterruptHandlers/VGA/VgaBios.cs, src/Spice86.Core/Emulator/InterruptHandlers/VGA/VgaRom.cs, src/Spice86.Core/Emulator/InterruptHandlers/VGA/VideoModeChangedEventArgs.cs, src/Spice86.Core/Emulator/Sound/Blaster/Dsp.cs, src/Spice86/Infrastructure/AvaloniaKeyScanCodeConverter.cs
Introduces Frozen collections (new in .NET 8) for lookup tables in the YM7128B module (unused, for the Adlib Gold) and the UI's Keyboard converter. Those new Frozen collections are made for lookup tables, and are supposed to be very fast. They are also truly immutable and cannot be changed after program initialization, unlike previous ReadOnlyList (you could access the underlying List via a simple cast) or Immutable (it accepted Add/Remove operations, but returned a new separated instance. It also was way too slow for lookup tables) collection types.
It also adds a few readonly record structs in the VGA namespace, removes a few unused arguments, unused imports, and obsolete XML documentation.
Prepares the future Adlib Gold PR for Dune, which will use the YM7128B module.
I already tested …
=> Introduce FrozenDictionnary/Set for most lookup tables

.github/workflows/pr.yml, src/Spice86/ViewModels/MainWindowViewModel.cs
This PR contains a bug fix for a crash on app exit, and the start of the MainWindowsViewModel split up into several ViewModels (as the class is too big)
The second part will follow later in another PR.
=> Fix: UI crash on app exit and refactor: UI _drawAction became a method

src/Spice86.Shared/Spice86.Shared.csproj, src/Spice86.Shared/UI/AdditionalWindow.cs
Tested successfully with Cryogenic.
This is to display anything from user code in a new custom window (or several).
Cryogenic will display live savegame data while Dune runs. And certainly other things later.
=> Simple support for additionnal windows from users

.github/workflows/nuget.yml, src/Bufdio.Spice86/Bufdio.Spice86.csproj, src/Spice86.Core/Spice86.Core.csproj, src/Spice86.Logging/Spice86.Logging.csproj, src/Spice86.Shared/Spice86.Shared.csproj, src/Spice86/Spice86.csproj
Software Mixer, SB Hardware Mixer, AdditionalWindows API for user code.
The merge of this release will trigger the creation of a new version of the Nuget packages.
The reason behind this release is to make the latest features usable with Cryogenic, most notably to work on Dune savegames.
=> Release: Spice86 v6.4.0

.github/workflows/nuget.yml, src/Bufdio.Spice86/Bufdio.Spice86.csproj, src/Spice86.Core/Spice86.Core.csproj, src/Spice86.Logging/Spice86.Logging.csproj, src/Spice86.Shared/Spice86.Shared.csproj, src/Spice86/Spice86.csproj
6.4.2 Nuget hotfix release for the vastly improved audio performance, especially regarding PCM audio.
=> Spice86: v6.4.2

.github/workflows/nuget.yml, src/Bufdio.Spice86/Bufdio.Spice86.csproj, src/Spice86.Core/Spice86.Core.csproj, src/Spice86.Logging/Spice86.Logging.csproj, src/Spice86.Shared/Spice86.Shared.csproj, src/Spice86/Spice86.csproj
For usage with Cryogenic or Krondor or other project via Nuget.
There are some breaking API changes (for Cryogenic, at least), hence the SemVer jump to v7.0.0
=> Spice86: v7.0.0

src/Spice86.Core/Emulator/CPU/CPU.cs, src/Spice86.Core/Emulator/CPU/Stack.cs, src/Spice86.Core/Emulator/Function/CircularBuffer.cs, src/Spice86.Core/Emulator/Function/Dump/GhidraSymbolsDumper.cs, src/Spice86.Core/Emulator/Function/ExecutionFlowRecorder.cs, src/Spice86.Core/Emulator/Function/FunctionHandler.cs, src/Spice86.Core/Emulator/Gdb/GdbIo.cs, src/Spice86.Core/Emulator/IOPorts/DefaultIOPortHandler.cs, src/Spice86.Core/Emulator/IOPorts/IOPortDispatcher.cs, src/Spice86.Core/Emulator/InterruptHandlers/Dos/DosInt21Handler.cs, src/Spice86.Core/Emulator/InterruptHandlers/Dos/Ems/ExpandedMemoryManager.cs, src/Spice86.Core/Emulator/InterruptHandlers/VGA/VgaBios.cs, src/Spice86.Core/Emulator/LoadableFile/Dos/Exe/ExeLoader.cs, src/Spice86.Core/Emulator/OperatingSystem/DosFileManager.cs, src/Spice86.Core/Emulator/OperatingSystem/DosMemoryManager.cs, src/Spice86.Core/Emulator/OperatingSystem/Structures/DosMemoryControlBlock.cs, src/Spice86.Core/Emulator/ReverseEngineer/ArgumentFetcher.cs, src/Spice86.Core/Emulator/ReverseEngineer/CSharpOverrideHelper.cs, src/Spice86.Logging/LoggerService.cs, src/Spice86.Shared/Emulator/Memory/SegmentedAddress.cs
A bunch of changes I had lying around my branch for ages.
- Some formatting
- Recording and dumping the mopst recently executed addresses. Helpt to debug Cpu Failures.
- Record and allow dumping of callstack, also helps a lot in debugging
- LogLevel changes to reduce noise
- An ArgumentFetcher to help getting the arguments passed into overridden functions.
- A "DoOnMemoryWrite" breakpoint setter for the CSharpOverrideHelper
- Add a Peek function for a byte.
- Mayeb some other small changes.
It's mostly small tweaks to make my life easier during reverse engineering of Krondor and debugging of Spice86.
Feel free to comment on stuff that should definitly not go into Spice86 and I'll keep those in my own branch.
Otherwise it'd be nice if we all work from mostly the same core codebase.
Run …
=> Sync master branches

src/Spice86.Core/Emulator/CPU/CfgCpu/Feeder/CurrentInstructions.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/Feeder/DiscriminatorReducer.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/InstructionExecutor/ModRmComputer.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/Linker/NodeLinker.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/ParsedInstruction/CfgInstruction.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/ParsedInstruction/Discriminator.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/ParsedInstruction/FieldWithValue.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/ParsedInstruction/InstructionField.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/Parser/FieldReader/InstructionFieldReader.cs, tests/Spice86.Tests/CfgCpu/CfgNodeFeederTest.cs, tests/Spice86.Tests/CfgCpu/InstructionsFeederTest.cs
All games seem to work apart for some crashes linked to discriminated node.
=> Fix CfgCpu bug where self modifying code changing just an instruction field would result in instruction change not beeing detected

src/Spice86.Logging/LoggerService.cs, src/Spice86.Logging/Spice86.Logging.csproj, src/Spice86.Shared/Spice86.Shared.csproj
=> refactor: removed unused enricher Serilog.Exceptions from logger

src/Spice86.Core/Spice86.Core.csproj, src/Spice86/Spice86.csproj
Because dependabot is still broken.
=> chore: upgraded CommunityToolkit MVVM Nuget package

src/Spice86.Core/Emulator/CPU/CfgCpu/CfgCpu.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/ExecutionContextManager.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/Feeder/CfgNodeFeeder.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/Feeder/CurrentInstructions.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/Feeder/DiscriminatorReducer.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/Feeder/IInstructionReplacer.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/Feeder/InstructionReplacer.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/Feeder/InstructionReplacerRegistry.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/Feeder/InstructionsFeeder.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/Feeder/PreviousInstructions.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/Linker/ExecutionContext.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/Linker/NodeLinker.cs, src/Spice86.Core/Emulator/CPU/InterruptVectorTable.cs, src/Spice86.Core/Emulator/ProgramExecutor.cs, src/Spice86.Core/Emulator/ReverseEngineer/DataStructure/Array/MemoryBasedArray.cs, src/Spice86.Core/Emulator/VM/EmulationLoop.cs, src/Spice86/Spice86DependencyInjection.cs, tests/Spice86.Tests/CfgCpu/CfgNodeFeederTest.cs, tests/Spice86.Tests/CfgCpu/InstructionsFeederTest.cs
No dune crash with cfgcpu with this pr
=> Fix CfgCpu messing up graph on external interruptions. Make interrupt vector table a memory based array.

src/Spice86.Core/CLI/Configuration.cs, src/Spice86.Core/Emulator/ProgramExecutor.cs
This new command line config --Debug (no short version), starts the program paused (for usage with the internal debugger)
=> feature: Internal Debugger: Start program paused

.github/workflows/codeql.yml, .github/workflows/nuget.yml, .github/workflows/pr.yml, .github/workflows/prerelease.yml, src/Bufdio.Spice86/Bufdio.Spice86.csproj, src/Directory.Build.props, src/Directory.Packages.props, src/Spice86.Core/Spice86.Core.csproj, src/Spice86.Logging/Spice86.Logging.csproj, src/Spice86.Shared/Spice86.Shared.csproj, src/Spice86.sln, src/Spice86/MemoryWrappers/DataMemoryDocument.cs, src/Spice86/Spice86.csproj, tests/Directory.Packages.props, tests/Spice86.Tests/Spice86.Tests.csproj
Draft for now as the performance seems to be worse. Tests are welcome.
Edit: performance seems to be the same after all according to @kevinferrare
=> chore: Migration to .NET 9 SDK

src/Spice86.Core/Emulator/Devices/Video/Renderer.cs, src/Spice86.Core/Emulator/Devices/Video/VideoMemory.cs, src/Spice86.Core/Emulator/Gdb/GdbCommandHandler.cs, src/Spice86.Core/Emulator/InterruptHandlers/Common/MemoryWriter/MemoryAsmWriter.cs, src/Spice86.Core/Emulator/InterruptHandlers/Dos/DosInt21Handler.cs, src/Spice86.Core/Emulator/InterruptHandlers/VGA/VgaFunctionality.cs, src/Spice86.Core/Emulator/OperatingSystem/DosPathResolver.cs
Changes private signatures and private variables to use concrete types instead of interfaces when possible.
Some lines replace the usage of LINQ with direct collection properties, such as the Any extension method begin replaced with List.Count
Doesn't measurably improves performance, but makes VS shut up about it.
=> chore: CA1859, CA1860 warnings fix

.github/workflows/nuget.yml, src/Directory.Build.props, src/Spice86/Views/DebugWindow.axaml
v8.0.0 of the Spice86 Nuget Package for Cryogenic and people who want to use a Release version of Spice86 via Nuget.
There has been a lot of breaking changes for users around dependency injection, a lot of new features for the internal debugger, justifying a new Nuget release.
Cryogenic already has a branch set up to use the latest Spice86 code. It still works.
=> chore: v8.0.0 Nuget Release

src/Spice86/MemoryWrappers/DataMemoryDocument.cs, src/Spice86/MemoryWrappers/MemoryReadOnlyBitRangeUnion.cs
This code was generating an IndexOutOfRangeException error when scrolling at the end of the Memory document in the Internal Debugger's memory tab.
=> fix: Off by one error

.github/workflows/nuget.yml, src/Directory.Build.props
Following the off-by-one-error hotfix, this ensures that a new Nuget (v8.0.2) is published
=> chore: Spice86 Nuget v8.0.2 hotfix

.github/workflows/codeql.yml, .github/workflows/nuget.yml, .github/workflows/pr.yml, .github/workflows/prerelease.yml, README.md, src/Directory.Build.props, src/Directory.Packages.props, tests/Directory.Packages.props
.NET 9 prevents Rider (at least on some machines) from building Spice86. Those machines include @kevinferrare 's machine, and it is a blocking issue and not acceptable.
The problem is documented on the JetBrains' side of things, but in the meantime going back to .NET 8 is an easy fix.
Try to build the solution with Rider. It should build with .NET 8.
'dotnet build' works either way, the issue is with .NET 9 support from JetBrains Rider itself.
=> fix: Rider has build issues with .NET 9

src/Spice86.Core/Emulator/Devices/DirectMemoryAccess/DmaController.cs, src/Spice86.Core/Emulator/Devices/Sound/Blaster/SoundBlaster.cs, src/Spice86.Core/Emulator/InterruptHandlers/Dos/DosInt21Handler.cs, src/Spice86.Core/Emulator/Memory/DmaChannel.cs, src/Spice86.Core/Emulator/OperatingSystem/Dos.cs, src/Spice86.Core/Emulator/OperatingSystem/Structures/DosSwappableDataArea.cs, src/Spice86.Core/Emulator/ProgramExecutor.cs, src/Spice86.Core/Emulator/VM/EmulationLoop.cs, src/Spice86.Core/Emulator/VM/Machine.cs, src/Spice86/Spice86DependencyInjection.cs
Implements:
- The DOS INDOS flag (described as 'number of calls to INT21H' in DOSBox source code).
-> DOSBox doesnt increment it ever, so we don't either.
Reason: DOS INT21H 0x34 (Get INDOS flag address) is called by SNDBLAST.DRV
Changes:
- Removes the DMA  Thread Loop
-> This did not impact performance. I guess my current PC is... current. And not from 2016.
-> So it manages Dune's intro, Dune's ingame, and Krondor intro and ingame voices without this ugly hack.
-> A DMA Thread has always been a crazy thing.
-> With it, the SNDBLAST.DRV made an infinite loop. Without it, the game started.
-> With it, it seems that the site of the crash was always random in Release mode. INT8H, INT2F, Unitialized Vector error, somewhere else...
Adds:
- 0xFF is returned when DspPort.Reset (0x266) is read …
=> Fix: Betrayal at Krondor SOUND BLASTER driver support (SNDBLAST.DRV)

src/Spice86.Core/Emulator/Devices/DirectMemoryAccess/DmaController.cs, src/Spice86.Core/Emulator/Memory/DmaChannel.cs
Delay the completion signal for single dma transfers by CPU 20 cycles.
It gives Krondor the chance to detect the IRQ used by the SoundBlaster.
Run games, check sounds.
=> Delay the completion signal for single dma transfers

src/Spice86.Core/Emulator/LoadableFile/Dos/Exe/ExeFile.cs, src/Spice86.Core/Emulator/LoadableFile/Dos/Exe/ExeLoader.cs
The size of the program image might not match the full size of the exe
file.
Calculate the correct size using the information in the MZ header.
Use the formula at
https://moddingwiki.shikadi.net/wiki/EXE_Format#Machine_code ,
except that (as opposed to what said in that page) the result is the
total size of header + code. To get the pure code length we still must
subtract the header size.
=> Fix program size

src/Spice86.Core/Emulator/Gdb/GdbCommandBreakPointHandler.cs, src/Spice86.Core/Emulator/Gdb/GdbCommandHandler.cs, src/Spice86.Core/Emulator/Gdb/GdbServer.cs
This fixes notifications of pauses from the emulator to the gdb client.
That is, when one pauses the emulator from outside the GDB client (namely, the spice86 UI), GDB is notified.
This makes the GDB command prompt available again.
=> fix: Notification of pauses from emulator to GDB client

src/Spice86.Core/Emulator/Gdb/GdbCommandMemoryHandler.cs
* calculate the correct indexes for the pattern to search
* encode the output address correctly (do not swap endianness, since we are sending back text)
The search was broken before; Spice86 would crash with a “index out of bounds” error and not return the correct addresses
Start executable with debug option, connect gdb and enter 
```
find /w3 0x0, 0xFFFFF, 0x00, 0x00
```
The expected output should be 
```
0x0
0x1
0x2
```
Go to Spice86's debugger. Select Memory/Edit
Address: 0100:0000
Bytes: 6161610061616100
Connect gdb and type
```
find /2 0x0, 0xFFFF, "aaa"
```
The expected output is
```
0x1001
0x1005
```
Note that Spice86 has slightly misplaced the bytes -- this is anyway irrelevant, the important thing is that the search succeeds returning 2 results.
=> GdbCommandMemoryHandler: fix SearchMemory

src/Spice86.Core/Emulator/Gdb/GdbCommandHandler.cs
If gdb tries to connect to Spice86 using `extended-remote` (instead of just `remote`), it will send a `!` command (request to activate extended mode).
The default answer of Spice86 is an empty response, which is not acknowledged by the gdb client as valid response to this request.
Change the command handler so that it outputs an error response (with an arbitrary error code). In this way, gdb recognizes that the extended mode is not supported, does not try to enable it and moves on in normal mode.
This fixes the connection problems with Seer, which uses extended-remote to connect.
Start Spice86 with `--GdbPort`, then start Seer. Configure Seer to connect to Spice86 (see https://github.com/OpenRakis/Spice86/pull/1071 for tips), then click launch. The connection should be almost …
=> GdbCommandHandler: reply to extended mode request with error message

src/Spice86/ViewModels/MainWindowViewModel.cs, src/Spice86/ViewModels/PerformanceViewModel.cs
DispatcherPriority.MaxValue was bad and could freeze the UI in some cases.
Especially when the game was in a hot loop waiting for something.
Exemple with 'Where in the World is Carmen Sandiego (1989)':
Before:
After:
=> fix: semi-UI freeze

src/Spice86.Core/Emulator/InterruptHandlers/VGA/VgaFunctionality.cs
VGA Bios is doing 2 memset to clear the screen, this doesnt sound right
Dune and stunts are working with that
=> Memset16 is done twice in VGA BIOS

src/Spice86.Core/Emulator/Devices/DeviceThread.cs, src/Spice86.Core/Emulator/Devices/Sound/Blaster/SoundBlaster.cs, src/Spice86.Core/Emulator/Devices/Sound/Midi/GeneralMidiDevice.cs, src/Spice86.Core/Emulator/Devices/Sound/Midi/MT32/Mt32MidiDevice.cs, src/Spice86.Core/Emulator/Devices/Sound/Midi/Midi.cs, src/Spice86.Core/Emulator/Devices/Sound/PCSpeaker/PcSpeaker.cs, src/Spice86.Core/Emulator/Devices/Sound/Ymf262Emu/OPL3FM.cs
Devices that require threads were handling them on their own with duplicated code (all are sound devices).
This expands the use of DeviceThread class used for PC speaker.
More robust thread handling in devices
Unified logging for device start
Sound threads all pause when the emulator pauses
Tested:
- midi and mt32 with dune
- soundblaster with dune
- pc speaker with prince of persia and stunts
- OPL3FM with prince of persia and krondor
=> Use device thread instead of duplicating thread implementation for each device that needs a thread

src/Spice86.Core/Emulator/Gdb/GdbCommandBreakPointHandler.cs, src/Spice86.Core/Emulator/VM/IPauseHandler.cs, src/Spice86.Core/Emulator/VM/PauseHandler.cs, src/Spice86/ViewModels/CfgCpuViewModel.cs, src/Spice86/ViewModels/CpuViewModel.cs, src/Spice86/ViewModels/DebugWindowViewModel.cs, src/Spice86/ViewModels/DisassemblyViewModel.cs, src/Spice86/ViewModels/MainWindowViewModel.cs, src/Spice86/ViewModels/MemoryViewModel.cs, src/Spice86/ViewModels/PerformanceViewModel.cs, src/Spice86/ViewModels/StructureViewModel.cs
Added "Paused" event for systems that want to react on the system finishing entering the paused state.
Moved UI systems from "Pausing" event (which signals the start of enetering the paused state) to "Paused".
"Pausing" is for systems that need to do something before a pause can take full effect.
"Paused" is for systems that want to react to the system having become paused.
UI systems using Pausing could read values from the CPU while it was not yet paused. The debugger got confused when the values from the current cpu state did not match the values read when the Pausing event was handled.
Use the debugger to see if behaviour is consistent now.
=> Fix pause events

src/Spice86.Core/Emulator/CPU/CfgCpu/ExecutionContextManager.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/Feeder/CurrentInstructions.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/Feeder/MemoryInstructionMatcher.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/ParsedInstruction/SelfModifying/DiscriminatedNode.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/Parser/FieldReader/InstructionFieldReader.cs, src/Spice86.Core/Emulator/Function/Dump/GhidraSymbolsDumper.cs, src/Spice86.Core/Emulator/Function/ExecutionFlowRecorder.cs, src/Spice86.Core/Emulator/Function/FunctionHandler.cs, src/Spice86.Core/Emulator/InterruptHandlers/Common/MemoryWriter/MemoryAsmWriter.cs, src/Spice86.Core/Emulator/InterruptHandlers/Common/MemoryWriter/MemoryWriter.cs, src/Spice86.Core/Emulator/InterruptHandlers/Input/Mouse/BiosMouseInt74Handler.cs, src/Spice86.Core/Emulator/InterruptHandlers/Input/Mouse/MouseDriver.cs, src/Spice86.Core/Emulator/InterruptHandlers/InterruptHandler.cs, src/Spice86.Core/Emulator/InterruptHandlers/VGA/VgaFunctionality.cs, src/Spice86.Core/Emulator/ReverseEngineer/CSharpOverrideHelper.cs, src/Spice86.Shared/Emulator/Memory/SegmentedAddress.cs, src/Spice86.Shared/Utils/ConvertUtils.cs, src/Spice86/MemoryWrappers/InstructionsDecoder.cs, src/Spice86/Messages/AddressChangedMessage.cs, src/Spice86/ViewModels/CfgCpuViewModel.cs, src/Spice86/ViewModels/DebugWindowViewModel.cs, src/Spice86/ViewModels/StructureViewModel.cs, src/Spice86/Views/StructureView.axaml.cs
- It's now truly immutable and never needs to recalculate the linear address.
- The addition and subtraction operators got bug fixes for over and underflows.
- A bunch of other comparison operators were added.
- Some constructs that assumed SegmentedAddress was mutable or a reference type were fixed.
If the SegmentedAddress is more flexible and easier to use, then perhaps it'll be easier to keep address segments for longer before converting them to uints
I ran Krondor and Dune for a bit and noticed no issues.
=> Segmented address improvements

src/Spice86.Core/Emulator/InterruptHandlers/Dos/DosInt21Handler.cs
DOS warns on process exit.
Helps detect games that are not supported. Well, some of them.
This is only a log line level change.
=> refactor: INT21 warns when a program has exited

README.md, doc/spice86.seer
Add a config file for Seer
Provides an easy way to use Seer with Spice86
Start Spice86 with `--GdbPort=10000`, and Seer with `seergdb --project ${SPICE86ROOT}/doc/spice86.seer`
=> Add Seer config file

src/Spice86/Spice86DependencyInjection.cs, src/Spice86/ViewModels/DisassemblyViewModel.cs
The functions information dict reference is passed to the UI, instead of making a new dictionary.
More over, the types within the dictionnaries were the same anyway.
This ensures that new functions discovered by the emulator are actually displayed in the functions combo box.
The AvalonaList behind it is updated for the benefit of the UI when the emulator is paused.
Already tested with Cryogenic:
=> fix: Pass reference to functions dict

src/Spice86.Core/Emulator/Devices/Sound/Blaster/HardwareMixer.cs, src/Spice86.Core/Emulator/Devices/Sound/Blaster/SbType.cs, src/Spice86.Core/Emulator/Devices/Sound/Blaster/SoundBlaster.cs, src/Spice86.Core/Emulator/Devices/Sound/Blaster/SoundBlasterHardwareConfig.cs, src/Spice86/Spice86DependencyInjection.cs
Fixes Lost Eden sound support.
Lost Eden (1995) is a Cryo game. its game engine is very close to Dune (1992).
It just replaces the Fremen with dinosaurs, essentially.
Lost Eden FM Synth and PCM support is fixed:
All I had to is to return 0xFF when it tries to read the soundblaster's MPU-401 port, and set the soundBlaster IRQ to 5, which is the _factory_ default that all **real mode games** expect.
Command line parameters:
`-f -d false -e "C:\GOG Games\Lost Eden\EDENPRG.EXE" -a "ENG SDB2225"`
Also works with EMS:
`-f -d false -e "C:\GOG Games\Lost Eden\EDENPRG.EXE" -a "ENG SDB2225 EMS" --Ems`
Also works well with the CFGCPU:
`--CfgCpu true -f -d false -e "C:\GOG Games\Lost Eden\EDENPRG.EXE" -a "ENG SDB2225 EMS" --Ems`
=> Fix: Lost Eden SB PCM and SB Music support

src/Spice86.Core/Emulator/Devices/Video/VideoMemory.cs
Throws `UnrecoverablException `instead of using `Debug.Assert`
Makes the UI not crash. We log the exception, and report it to the user instead.
Already tested with Wizardry 7 (which doesn't work ATM).
=> fix: Don't crash with assert, throw instead

src/Spice86.Core/Emulator/CPU/CfgCpu/ControlFlowGraph/CfgNode.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/ControlFlowGraph/ICfgNode.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/Feeder/CfgNodeFeeder.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/Feeder/CurrentInstructions.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/ParsedInstruction/CfgInstruction.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/ParsedInstruction/SelfModifying/DiscriminatedNode.cs
Each cycle, the CFG CPU needs to know whether the next node it got from graph execution is really what is in memory.
This was done via a dictionary lookup.
With this change, all nodes have a field indicating whether it is "live" or not. Live means it is in memory for instructions.
The field is managed when instruction is moved out of current pool (self modifying code).
This makes code a bit faster and will allow the UI to represent live nodes differently in the future.
Tested with dune and Krondor, noticed a slight performance increase.
=> Add a field in all nodes to represent whether the node is aligned with the current state of the machine. This makes CfgCpu slightly faster.

src/Spice86.Core/Emulator/CPU/CfgCpu/Feeder/CurrentInstructions.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/ParsedInstruction/FieldWithValue.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/ParsedInstruction/InstructionField.cs
Instruction fields are usually read directly from instruction parsing, but if self modifying code modifies a field, subsequent reads are done from memory.
This change ensures we don't detect writes into a fields that is already read from memory as self modifying code.
Reduces the number of times an instruction is going to be re-created.
Works with krondor and dune
=> Do not create breakpoints on fields that are already read from memory to detect self modifying code.

src/Spice86.Core/Emulator/CPU/CfgCpu/ControlFlowGraph/NodeToString.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/Feeder/CfgNodeFeeder.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/Linker/NodeLinker.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/ParsedInstruction/SelfModifying/SelectorNode.cs, src/Spice86/ViewModels/CfgCpuViewModel.cs, tests/Spice86.Tests/CfgCpu/CfgNodeFeederTest.cs, tests/Spice86.Tests/CfgGraphDumper.cs
Discriminated was a bad name, selector reflect better what it does
Also factorized code that transform node to string
=> Rename discriminated node to selector node which is a better name.

src/Spice86.Core/Emulator/InterruptHandlers/SystemClock/SystemClockInt1AHandler.cs
SystemClockInt1AHandler (INT 1A) has switched Get and Set calls.
This PR simply changes 0 <-> 1 to assign proper handlers to calls.
https://stanislavs.org/helppc/int_1a.html
* `INT 1A` `AH=0`: Read system clock counter
* `INT 1A` `AH=1`:  Set system clock counter
I tested it on game Warlords.
Before the fix, it got stuck in the loading phase, printing "SET SYSTEM CLOCK COUNTER" in logs but in the debugger, I clearly see AH=0 for `INT 0x1A` syscall.
After the fix, I got into the main screen:
=> Int1A - SystemClock - Fix incorrectly assigned call numbers

src/Spice86.Core/Emulator/Devices/Sound/Ymf262Emu/FmSynthesizer.cs, src/Spice86.Core/Emulator/Devices/Sound/Ymf262Emu/OPL3FM.cs
A small PR to use a low pass filter on the Sound Blaster FM Synth music output. Config taken from DOSBox Staging source code.
Uses a hardcoded SB PRo 2 configuration for now: the cut off freq is 8000 Hz.
Tested with Dune and Krondor.
For better performance, it also removes a loop from Mono to Stereo processing. The sample are directly stereo, and directly processed by the low pass filter.
=> Feature/opl3 filters (Dune and Krondor FM Synth music sound better)

src/Spice86.Core/Emulator/VM/EmulationLoop.cs, src/Spice86.Shared/Diagnostics/PerformanceMeasurer.cs, src/Spice86.Shared/Interfaces/IPerformanceMeasurer.cs, src/Spice86/Spice86DependencyInjection.cs, src/Spice86/ViewModels/CfgCpuViewModel.cs, src/Spice86/ViewModels/PerformanceViewModel.cs
Fixes Lost Eden voices being unbearable to the ears.
performance measurement was degrading performance
Details:
- Updated `EmulationLoop` to expose `CpuPerformanceMeasurer` and share it that way in dependency injection step with the PerformanceViewModel constructor.
- Split `IPerformanceMeasurer` into `IPerformanceMeasureReader` and `IPerformanceMeasureWriter`for better interface segragation.
- Updated `PerformanceViewModel` to use `IPerformanceMeasureReader` and accept a `cpuPerfReader` parameter.
- Removed `performanceMeasurer` parameter from `CfgCpuViewModel` constructor. It creates an instance internally, because this instance measures internal performance of the class.
- Improved code formatting in `PerformanceMeasurer` to respect 80 columns limit.
Already tested with Lost Eden and …
=> fix: performance measurement was degrading performance

src/Spice86.Core/Emulator/InterruptHandlers/Dos/DosInt21Handler.cs, src/Spice86.Core/Emulator/InterruptHandlers/SystemClock/SystemClockInt1AHandler.cs, src/Spice86.Core/Emulator/OperatingSystem/Clock.cs, src/Spice86.Core/Emulator/OperatingSystem/Dos.cs, src/Spice86/Spice86DependencyInjection.cs, tests/Spice86.Tests/Dos/DosFileManagerTests.cs, tests/Spice86.Tests/Emulator/OperatingSystem/ClockTest.cs
Implementation of interrupt handlers for setting and getting date/time.
The RTC is a fake one (for now), but it should be fine for our use case unless a "real" RTC has to be implemented.
The game "Tom Long" crashed without those handlers
I started Tom Long and watched it get and set the date/time.
=> Add date/time related interrupt handlers

src/Spice86.Core/Emulator/OperatingSystem/DosStringDecoder.cs
An exception was thrown randomly while I tried to run "Another World". The end character was not found within 0..MaxDosStringLength. Strangely, I could not reproduce the issue afterwards but its better to fix it.
The string handling is also slightly improved.
I also thought about resizing the array if needed but would leave that open for discussion.
Prevent possible OutOfBounds exception
Random exception while trying to run "Another World"
I just started "Another World" but somehow, the error disappeared.
=> fix out-of-bounds risk in GetDosString and simplify string handling

src/Spice86.Core/Emulator/OperatingSystem/DosFileManager.cs
I debugged/traced how DosBox treats issues if a file can not be found in FindFirstMatchingFile. It turns out that the correct error code would is "NoMoreFiles". I also have a suspicion why the game does it. I assume there is a possibility to overwrite the games assets, which are in the data.-1- file, with files in the same directory. As we are returning the wrong error code, it would loop indefinitely.
In IDA, I can also see that it compares against 0x12 / dec 18:
Here is a proof that it works now.
Improve compatibility by returning the correct error code.
Launch EnviroKids
=> fix incorrect error code if FindFirstMatchingFile fails

src/Spice86.Core/Emulator/InterruptHandlers/Input/Keyboard/KeyboardInt16Handler.cs, src/Spice86.Core/Emulator/InterruptHandlers/Input/Mouse/MouseInt33Handler.cs, src/Spice86.Core/Emulator/OperatingSystem/DosFileManager.cs
This PR will enhance the compatibility for multiple games, like "Das Telekommando" for example.
Enhanced compatibility, fallback for undocumented/unsupported keyboard operations according to https://stanislavs.org/helppc/int_16.html
Mouse reset is required for "Batman Returns". 
The correct treatment of an unsupported keyboard feature is debatable, but in my opinion, it should be alright. I could not find a proper documentation in that case.
=> Several compatibility fixes

src/Spice86/ViewModels/IRegistersViewModel.cs, src/Spice86/ViewModels/RegistersViewModel.cs, src/Spice86/Views/RegistersView.axaml
Adds a numeric view of the CPU flag value in debugger
Useful for debugging the emulator itself
=> Display Flags numeric content in debug view

src/Spice86.Core/Emulator/InterruptHandlers/Dos/DosInt21Handler.cs, src/Spice86.Core/Emulator/OperatingSystem/Dos.cs, src/Spice86.Core/Emulator/OperatingSystem/DosFileManager.cs, src/Spice86.Core/Emulator/OperatingSystem/DosMemoryManager.cs, src/Spice86.Core/Emulator/OperatingSystem/DosPathResolver.cs, src/Spice86.Core/Emulator/OperatingSystem/DosProcessManager.cs, src/Spice86.Core/Emulator/OperatingSystem/Enums/DosErrorCode.cs, src/Spice86.Core/Emulator/OperatingSystem/Structures/DosFileOperationResult.cs, src/Spice86.Core/Emulator/OperatingSystem/Structures/DosMemoryControlBlock.cs, src/Spice86.Core/Emulator/OperatingSystem/Structures/DosProgramSegmentPrefix.cs, src/Spice86.Core/Emulator/OperatingSystem/Structures/DosSysVars.cs
Makes DosMemoryManager and DosProcessManager more object oriented.
Clarifies a lot about DOS MCB with renamed properties and documentation.
Makes ModifiyBlock return the proper error code if the MCB is destroyed.
DosProcessManager has a CurrentPsp property now.
Those refactoring enable more refactorings later to support:
- Games demanding 604+ KB of free conv. memory (for example: Tom Long)
- DOS Processes
- TSRs
Already tested with prince of persia, Dune, Krondor, Dune 2, and PoP2 (well, until it stops because of other bugs)
=> refactor: DosMemoryManager, DosMemoryControlBlock, ModifyBlock, DosProcessManager

src/Spice86/Spice86DependencyInjection.cs, src/Spice86/ViewModels/HeadlessGui.cs
The original implementation did not use a GUI, which made it so that applications behave differently in headless mode - some waiting for certain register values for example.
I noticed this difference in Space Job which throws an exception in GUI mode but just loops indefinitely in headless mode.
I also tried Avalonias Headless mode which also works fine but obviously requires more resources.
Introduce a headless GUI to simulate rendering at 60 Hz with a fake framebuffer.
Improve headless mode to behave similarly to GUI mode.
Run some games in headless mode.
=> Improve headless mode

src/Directory.Packages.props, src/Spice86.Core/CLI/Configuration.cs, src/Spice86.Core/CLI/HeadlessType.cs, src/Spice86/Program.cs, src/Spice86/Spice86.csproj, src/Spice86/Spice86DependencyInjection.cs, src/Spice86/ViewModels/MainWindowViewModel.cs, src/Spice86/ViewModels/Services/IExceptionHandler.cs
This MR adds Avalonias own headless mode which uses the same application lifecycle as the GUI-mode minus the rendering. This can be used for future end-to-end tests, for test automation and other fancy things.
As the default application would not exit on exceptions, I had to introduce a new exception handler which reacts to exceptions appropriately.
The user can start the headless mode in multiple ways:
-h | --HeadlessMode    =    Run with Default (fake Headless GUI)
-h Default | --HeadlessMode Default    =    Run with Default (fake Headless GUI)
-h Avalonia | --HeadlessMode Avalonia    =    Run with Avalonia Headless
More flexibility and a headless environment which is as close to the GUI as possible. It allows fancy things like taking screenshots, unit/integration tests and so on.
Run …
=> Feature: add Avalonia headless mode

src/Spice86.Core/Emulator/VM/EmulationLoop.cs, src/Spice86/ViewModels/MainWindowViewModel.cs
This PR tries to avoid having to call the high precision performance counter as much as possible, whose overhead is about 17%.
With those changes, the performance is roughly on par with master when the cycles are set very high.
=> cycle limiter performance optimizations

src/Spice86.Core/CLI/Configuration.cs, src/Spice86.Core/Emulator/OperatingSystem/Dos.cs, src/Spice86.Core/Emulator/OperatingSystem/Structures/DosSysVars.cs, src/Spice86/Spice86DependencyInjection.cs
A flaw in CommandLine when bool parameters are true by default, they can not be disable with false.
Now they can.
=> fix: EMS and XMS could not be disabled

src/Spice86.Core/Emulator/LoadableFile/Dos/DosExeFile.cs
The previous calculation was wrong and some games that used to work crashed.
Fix crash issues.
=> fix: correct image size calculation

src/Directory.Packages.props
reverts fluentIcons 'minor' upgrade from 303 to 309 for now, as it breaks master on font creation.
=> fix: package upgrade broke master (font resource ?)

src/Spice86.Core/Emulator/CPU/CPU.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/CfgCpu.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/ParsedInstruction/Instructions/Mixins/FlagControl.mixin, src/Spice86.Core/Emulator/CPU/CfgCpu/ParsedInstruction/Instructions/Mixins/PopReg.mixin, src/Spice86.Core/Emulator/CPU/CfgCpu/ParsedInstruction/Instructions/MovSregRm16.cs, src/Spice86.Core/Emulator/CPU/InstructionsImpl/Instructions16.cs, src/Spice86.Core/Emulator/CPU/State.cs
According to this documentation:
https://cdrdv2-public.intel.com/782161/326019-sdm-vol-3c.pdf
https://cdrdv2-public.intel.com/825750/326019-sdm-vol-3c.pdf
STI (if IF 0 => 1), MOV SS and POP SS need to inhibit the execution of interrupts.
This MR implements this behavior to prevent possible stack corruption.
Prevent bugs, may fix some compatibility issues.
=> Feature: implement interrupt shadowing

src/Spice86.Core/Emulator/InterruptHandlers/Input/Mouse/BiosMouseInt74Handler.cs, src/Spice86.Core/Emulator/InterruptHandlers/Input/Mouse/IMouseDevice.cs, src/Spice86.Core/Emulator/InterruptHandlers/Input/Mouse/MouseDriver.cs, src/Spice86.Core/Emulator/InterruptHandlers/Input/Mouse/MouseInt33Handler.cs, src/Spice86.Core/Emulator/InterruptHandlers/Input/Mouse/MouseStatus.cs
Some minor refactorings. There are five categories of changes:
- avoid local variable allocation of mouse buttons
- Documentation fix
- Safe inspection fixes
- Safety measures
- Real bugs (SetMouseMickeyPixelRatio, GetLastPressedY, GetLastReleasedY)
Regarding the real bugs:
**SetMouseMickeyPixelRatio**
I read the documentation and implementation and it should be divided by 8 instead of multiplied by 8.
**GetLastPressedY** & **GetLastReleasedY**
Both used LastPressedX instead of LastPressedY
Safety, correctness
=> fix: some minor mouse-related fixes and refactorings

src/Spice86/Spice86DependencyInjection.cs, src/Spice86/ViewModels/Services/HostStorageProvider.cs, src/Spice86/ViewModels/VideoCardViewModel.cs, src/Spice86/Views/VideoCardView.axaml
The Spice86 builtin debugger is able to display a lot of information about the video card state, which is very useful for tracking down video-related issues. However prior to this PR, it wasn't possible to easily copy it and compare snapshots of the video card state at different points in time without manually copying each field or transcribing it in some other way, which was painful and time-consuming.
Therefore this PR adds a new context menu to the video debugger view that allows the user to save the whole video card state to disk as a JSON file. That makes it possible to run through a JSON formatting tool like `jq` and `diff` it much more easily.
Thanks to @maximilien-noal for getting me started by making the properties on the video card view read-only for me!
**Video Card Info …
=> Add support for saving the video card info to a file
