src/Spice86/Emulator/CPU/CPU.cs
Changed the instruction dispatcher to use switch statements rather than cascaded `if`-statements.
=> Refactor: improved the instruction dispatcher

src/Spice86/Emulator/InterruptHandlers/Dos/DosFileManager.cs
=> DosFileManager: use Path.Combine instead of +

src/Spice86/Ui/ViewModels/MainWindowViewModel.cs, src/Spice86/Ui/Views/MainWindow.axaml
=> Use thread for Emulator Machine

src/Spice86/Ui/ViewModels/VideoBufferViewModel.cs, src/Spice86/Ui/Views/MainWindow.axaml.cs
=> Avoid error on exit, with event

src/Spice86/Emulator/Devices/Timer/Counter.cs
=> Counter: OnValueWrite call in SetValueUsingMode

src/Spice86/Emulator/Devices/Timer/CounterActivator.cs, src/Spice86/Emulator/Devices/Timer/Timer.cs, src/Spice86/Spice86.csproj, src/Spice86/Ui/ViewModels/MainWindowViewModel.cs, src/Spice86/Ui/Views/MainWindow.axaml
=> Time Multiplier: UI implemented

src/Spice86/Emulator/Gdb/GdbServer.cs
Might fix the bug in Debug mode where one can't
connect to the GdbServer.
Issue: https://github.com/OpenRakis/Spice86/issues/91
=> GdbServer: use waitHandle, backgroundWorker is a field

src/Spice86/CLI/CommandLineParser.cs, src/Spice86/Emulator/CPU/CPU.cs, src/Spice86/Emulator/Configuration.cs, src/Spice86/Emulator/VM/Machine.cs, src/Spice86/Program.cs
=> possible to set log level set at startup via command line

src/Spice86.Core/Emulator/Devices/Sound/Midi.cs, src/Spice86.Core/Emulator/Devices/Sound/SoundBlaster.cs, src/Spice86.Core/Emulator/IOPorts/DefaultIOPortHandler.cs, src/Spice86.Core/Emulator/Sound/Midi/GeneralMidi.cs, src/Spice86.Core/Emulator/Sound/Midi/MT32/Mt32MidiDevice.cs, src/Spice86.Core/Emulator/Sound/Midi/MT32/Mt32Player.cs, src/Spice86.Core/Emulator/VM/Machine.cs
=> MT-32: works again. A render thread was missing.

ghidraCodeGenerator/Spice86CodeGenerator.java
=> CodeGenerator: shorter XCHG translation with Tuples

src/Spice86/Program.cs
=> Headless Mode: exit on exception

.github/workflows/dotnet.yml, src/Bufdio.Spice86/Bufdio.Spice86.csproj, src/Spice86.Core/Emulator/CPU/Alu.cs, src/Spice86.Core/Spice86.Core.csproj, src/Spice86.Logging/Spice86.Logging.csproj, src/Spice86.Shared/Spice86.Shared.csproj, src/Spice86/Spice86.csproj
=> Fix: some ALU methods were static, this didnt make the generator happy

src/Spice86.Core/Emulator/Gdb/GdbIo.cs, src/Spice86.Core/Emulator/Gdb/GdbServer.cs, src/Spice86.Core/Emulator/VM/PauseHandler.cs, src/Spice86/ViewModels/MainWindowViewModel.cs
PauseHandler: Wait for ever, not 1ms (GDB)
- Fixes issue #219
=> PauseHandler: Wait for ever, not 1ms (GDB)

src/Spice86.Core/Emulator/CPU/Alu.cs, src/Spice86.Core/Emulator/CPU/CPU.cs, src/Spice86.Core/Emulator/CPU/InstructionsImpl/Instructions16.cs, src/Spice86.Core/Emulator/CPU/InstructionsImpl/Instructions16Or32.cs, src/Spice86.Core/Emulator/CPU/InstructionsImpl/Instructions32.cs, src/Spice86.Core/Emulator/InterruptHandlers/Dos/DosInt2fHandler.cs, src/Spice86.Core/Emulator/InterruptHandlers/Input/Mouse/MouseInt33Handler.cs, src/Spice86.Core/Emulator/VM/Machine.cs, src/Spice86.Tests/MachineTest.cs
- Implements LEAVE, MOVZX, MOVSX and SHLD opcodes.
- Adds SHOW MOUSE CURSOR and HIDE MOUSE CURSOR stubs
- Adds dos INT 2F handler
=> Additional opcodes and interrupt handlers

src/Spice86.Core/Emulator/InterruptHandlers/Dos/DosInt21Handler.cs, src/Spice86.Core/Emulator/LoadableFile/Dos/PspGenerator.cs, src/Spice86.Core/Emulator/Memory/Bios.cs, src/Spice86.Core/Emulator/Memory/MemoryMap.cs, src/Spice86.Core/Emulator/OperatingSystem/BlockDevice.cs, src/Spice86.Core/Emulator/OperatingSystem/CharacterDevice.cs, src/Spice86.Core/Emulator/OperatingSystem/DeviceAttributes.cs, src/Spice86.Core/Emulator/OperatingSystem/DeviceStream.cs, src/Spice86.Core/Emulator/OperatingSystem/Dos.cs, src/Spice86.Core/Emulator/OperatingSystem/DosDiskTransferArea.cs, src/Spice86.Core/Emulator/OperatingSystem/DosFileManager.cs, src/Spice86.Core/Emulator/OperatingSystem/DosFileOperationResult.cs, src/Spice86.Core/Emulator/OperatingSystem/DosMemoryControlBlock.cs, src/Spice86.Core/Emulator/OperatingSystem/DosMemoryManager.cs, src/Spice86.Core/Emulator/OperatingSystem/EnvironmentVariables.cs, src/Spice86.Core/Emulator/OperatingSystem/ErrorCode.cs, src/Spice86.Core/Emulator/OperatingSystem/IVirtualDevice.cs, src/Spice86.Core/Emulator/OperatingSystem/OpenFile.cs, src/Spice86.Core/Emulator/OperatingSystem/VirtualDeviceBase.cs, src/Spice86.Core/Emulator/ProgramExecutor.cs, src/Spice86.Core/Emulator/VM/Machine.cs
- Implement virtual devices and let DOS open them as stdin, stdout, etc.
- Introduce dos error codes.
- Add some more to the MemoryMap
- Started moving DOS data/variables to the now central location
=> - Introduce Dos class to manage DOS subsystems.

src/Spice86.Core/Emulator/CPU/CPU.cs, src/Spice86.Core/Emulator/CPU/InstructionsImpl/Instructions16.cs, src/Spice86.Core/Emulator/CPU/InstructionsImpl/Instructions16Or32.cs, src/Spice86.Core/Emulator/CPU/InstructionsImpl/Instructions32.cs, src/Spice86.Core/Emulator/InterruptHandlers/Dos/DosInt2fHandler.cs
Closes #250 
Fixes Lands Of Lore and Stunts 4D. Although, they don't run for other reasons (INT2F and VGA services not implemented, respectively)
=> CPU: ENTER instruction

src/Spice86.Core/Emulator/CPU/CPU.cs, src/Spice86.Core/Emulator/CPU/InstructionsImpl/Instructions16.cs, src/Spice86.Core/Emulator/CPU/InstructionsImpl/Instructions16Or32.cs, src/Spice86.Core/Emulator/CPU/InstructionsImpl/Instructions32.cs
Added the 0x0F 0xAF variation of the IMUL instruction.
No tests yet, will be done in #228
=> Imul instruction addition

src/Spice86.Core/Emulator/CPU/CPU.cs
=> Fix loglevel include

src/Spice86.Core/Emulator/InterruptHandlers/Dos/DosInt21Handler.cs, src/Spice86.Core/Emulator/InterruptHandlers/Dos/DosInt2fHandler.cs, src/Spice86.Core/Emulator/OperatingSystem/Dos.cs, src/Spice86.Core/Emulator/VM/Machine.cs
Makes Lands of Lore run until it demands XMS memory (because we have none at the moment).
=> INT2F: Reworked and added more fake services

src/Spice86.Core/Emulator/CPU/Flags.cs
Just moved members and functions to put them back in order
=> Reorganize the flags fields by their order in the FLAGS register

src/.editorconfig
New coding standard:
- put usings inside the namespace
- use fully qualified usings
=> Add rules for usings: Inside namespace + Fully Qualified

src/Spice86.Core/Emulator/Devices/Video/AeonCard.cs
Should fix Dune's LOGO.EXE garbled display.
=> Fix bug in palette

src/Spice86.Core/Emulator/CPU/CPU.cs, src/Spice86.Logging/LoggerService.cs
Replace ThreadId logging with logging of last non-bios address executed by the CPU.
=> Add CS:IP to logging

.github/workflows/codeql.yml
Don't run the CodeQL on macos and ubuntu, only ubuntu.
=> faster codeql scan

src/Spice86.Core/Emulator/Devices/DirectMemoryAccess/DmaController.cs, src/Spice86.Core/Emulator/Devices/Sound/SoundBlaster.cs, src/Spice86.Core/Emulator/Sound/Blaster/Dsp.cs, src/Spice86.Core/Emulator/Sound/Blaster/DspPorts.cs, src/Spice86.Core/Emulator/Sound/Blaster/DspState.cs
=> (Dune) Implement ports DSP_READ_STATUS and DSP_WRITE_STATUS

.github/dependabot.yml, .github/workflows/dotnet.yml, src/Bufdio.Spice86/Bufdio.Spice86.csproj, src/Spice86.Core/Spice86.Core.csproj, src/Spice86.Logging/Spice86.Logging.csproj, src/Spice86.Shared/Spice86.Shared.csproj, src/Spice86/Spice86.csproj
New release of Spice86, includes the .NET 8 upgrade.
=> Spice86 v6.2.0

.github/workflows/dotnet.yml
=> fix workflow: only publish Nuget from master

src/Spice86.Core/Emulator/CPU/CfgCpu/CfgCpu.cs, src/Spice86.Core/Emulator/CPU/CfgCpu/Linker/ExecutionContext.cs, src/Spice86.Core/Emulator/VM/Machine.cs, src/Spice86/Models/Debugging/CfgCpu/CfgNodeInfo.cs, src/Spice86/Spice86.csproj, src/Spice86/ViewModels/CfgCpuViewModel.cs, src/Spice86/ViewModels/DebugViewModel.cs, src/Spice86/ViewModels/MainWindowViewModel.cs, src/Spice86/ViewModels/PerformanceViewModel.cs, src/Spice86/Views/CfgCpuView.axaml, src/Spice86/Views/CfgCpuView.axaml.cs, src/Spice86/Views/DebugWindow.axaml, src/Spice86/Views/MainWindow.axaml
=> Feature/cfg cpu debug UI

src/Spice86.Core/CLI/CommandLineParser.cs, src/Spice86.Core/Emulator/Function/Dump/ExecutionFlowDumper.cs, src/Spice86.Core/Emulator/Gdb/GdbCommandBreakPointHandler.cs, src/Spice86.Core/Emulator/Gdb/GdbCommandMemoryHandler.cs, src/Spice86.Core/Emulator/Gdb/GdbCommandRegisterHandler.cs, src/Spice86.Core/Emulator/Gdb/GdbCustomCommandsHandler.cs, src/Spice86.Core/Emulator/Gdb/GdbServer.cs, src/Spice86.Core/Emulator/OperatingSystem/DosFileManager.cs, src/Spice86.Core/Emulator/ProgramExecutor.cs, src/Spice86.Core/Emulator/VM/EmulationLoop.cs, src/Spice86.Core/Emulator/VM/PauseHandler.cs, src/Spice86.Core/Spice86.Core.csproj, src/Spice86/Spice86.csproj, src/Spice86/ViewModels/MainWindowViewModel.cs, src/Spice86/ViewModels/ViewModelBaseWithErrorDialog.cs
=> fix: stacktraces (removed Ben.Demistify package)

src/Spice86.Core/Emulator/OperatingSystem/DosFileManager.cs
Fixes Prince of Persia crashing the emulator on a fileSpec.
=> fix: transform of 'C:????????.???' into '????????.???' fileSpec (PoP)

src/Spice86.Core/CLI/CommandLineParser.cs, src/Spice86.Core/CLI/ICommandLineParser.cs, src/Spice86/App.axaml.cs, src/Spice86/DependencyInjection/ServiceCollectionExtensions.cs, src/Spice86/Infrastructure/HostStorageProvider.cs, src/Spice86/Infrastructure/IHostStorageProvider.cs, src/Spice86/Interfaces/IPauseStatus.cs, src/Spice86/MemoryWrappers/CodeMemoryStream.cs, src/Spice86/MemoryWrappers/DataMemoryDocument.cs, src/Spice86/Program.cs, src/Spice86/ViewModels/DisassemblyViewModel.cs, src/Spice86/ViewModels/MainWindowViewModel.cs, src/Spice86/ViewModels/MemoryViewModel.cs, src/Spice86/Views/MainWindow.axaml
A PR that introduces DI-IoC for all the UI services, and the MainWindowViewModel, instead of having a ton of new in Program.cs
This is only a first pass. Next PR will resolve more dependencies from bottom components (CPU, PIC, ...) up to the top (UI ViewModels) all in Program.cs.
=> Refactoring: UI TopLevel services and MainWindowViewModel injection

src/Spice86/DependencyInjection/ServiceCollectionExtensions.cs, src/Spice86/Interfaces/IPauseStatus.cs, src/Spice86/Program.cs, src/Spice86/ViewModels/CfgCpuViewModel.cs, src/Spice86/ViewModels/CpuViewModel.cs, src/Spice86/ViewModels/DebugWindowViewModel.cs, src/Spice86/ViewModels/DisassemblyViewModel.cs, src/Spice86/ViewModels/MainWindowViewModel.cs, src/Spice86/ViewModels/MemoryViewModel.cs, src/Spice86/ViewModels/Messages/AddViewModelMessage.cs, src/Spice86/ViewModels/Messages/PauseStatusMessage.cs, src/Spice86/ViewModels/Messages/RemoveViewModelMessage.cs, src/Spice86/ViewModels/PaletteViewModel.cs, src/Spice86/ViewModels/PerformanceViewModel.cs
Introduces inversion of control for more of the UI code.
Centralizes dependency management in Program.cs.
Centralizes lifetime management in Program.cs
Makes the code base easier to change for the UI and internal debugger.
The next step will be the emulator project.
Test existing overrides, and supported games, and report regressions, if any.
This should not introduce any.
If there are some, it means that some lifetime choices (Singleton vs Scoped vs Transient) were in error.
Status: Done.
=> refactor: Inversion of control for all dependencies between classes in the UI

src/Spice86.Core/CLI/CommandLineParser.cs
Sucessfully tesed with Doom8088.
Fixes #526
=> Fix: dashes in passed cmdline args

src/Spice86.Logging/LoggerService.cs, src/Spice86.Logging/Spice86.Logging.csproj
Helps with reverse engineering and when we have to investigate emulation issues.
=> Feature: emulator logs to file

src/Spice86.Core/Emulator/Devices/DirectMemoryAccess/DmaController.cs, src/Spice86.Core/Emulator/Devices/Sound/Blaster/SoundBlaster.cs, src/Spice86.Core/Emulator/Devices/Sound/Midi/GeneralMidiDevice.cs, src/Spice86.Core/Emulator/Devices/Sound/Midi/MT32/Mt32MidiDevice.cs, src/Spice86.Core/Emulator/Devices/Sound/Midi/MT32/Mt32Player.cs, src/Spice86.Core/Emulator/Devices/Sound/Midi/Midi.cs, src/Spice86.Core/Emulator/Devices/Sound/SoftwareMixer.cs, src/Spice86.Core/Emulator/Devices/Sound/Ymf262Emu/OPL3FM.cs, src/Spice86.Core/Emulator/Gdb/GdbCommandBreakPointHandler.cs, src/Spice86.Core/Emulator/Gdb/GdbCommandHandler.cs, src/Spice86.Core/Emulator/Gdb/GdbServer.cs, src/Spice86.Core/Emulator/IProgramExecutor.cs, src/Spice86.Core/Emulator/InterruptHandlers/Dos/DosInt21Handler.cs, src/Spice86.Core/Emulator/InterruptHandlers/Dos/DosInt28Handler.cs, src/Spice86.Core/Emulator/OperatingSystem/Dos.cs, src/Spice86.Core/Emulator/ProgramExecutor.cs, src/Spice86.Core/Emulator/VM/EmulationLoop.cs, src/Spice86.Core/Emulator/VM/IPauseHandler.cs, src/Spice86.Core/Emulator/VM/Machine.cs, src/Spice86.Core/Emulator/VM/MachineBreakpoints.cs, src/Spice86.Core/Emulator/VM/PauseHandler.cs, src/Spice86/Infrastructure/ProgramExecutorFactory.cs, src/Spice86/Infrastructure/StructureViewModelFactory.cs, src/Spice86/Program.cs, src/Spice86/ViewModels/DebugWindowViewModel.cs, src/Spice86/ViewModels/MainWindowViewModel.cs, src/Spice86/ViewModels/StructureViewModel.cs, tests/Spice86.Tests/CfgCpu/CfgNodeFeederTest.cs, tests/Spice86.Tests/CfgCpu/InstructionsFeederTest.cs, tests/Spice86.Tests/MachineCreator.cs
Centralize and inject the PauseHandler so all threads, except Main and UI, can be paused.
I wanted to trigger a pause from my override code and then be able to resume it from the UI.
Play games, pause, debug, breakpoint, etc.
=> Pause handling

src/Directory.Packages.props, src/Spice86.Core/Emulator/Gdb/GdbCommandBreakPointHandler.cs, src/Spice86.Core/Emulator/VM/EmulatorBreakpointsManager.cs, src/Spice86/App.axaml, src/Spice86/Controls/GroupBox.cs, src/Spice86/Controls/StatusBar.cs, src/Spice86/Controls/StatusBarItem.cs, src/Spice86/Converters/BreakpointToBrushConverter.cs, src/Spice86/Mappers/MapperExtensions.cs, src/Spice86/MemoryWrappers/InstructionsDecoder.cs, src/Spice86/Models/Debugging/CpuInstructionInfo.cs, src/Spice86/Spice86.csproj, src/Spice86/Spice86DependencyInjection.cs, src/Spice86/ViewModels/BreakpointViewModel.cs, src/Spice86/ViewModels/BreakpointsViewModel.cs, src/Spice86/ViewModels/CpuViewModel.cs, src/Spice86/ViewModels/DebugWindowViewModel.cs, src/Spice86/ViewModels/DisassemblyViewModel.cs, src/Spice86/ViewModels/MemoryViewModel.cs, src/Spice86/ViewModels/MidiViewModel.cs, src/Spice86/ViewModels/PerformanceViewModel.cs, src/Spice86/ViewModels/StructureViewModel.cs, src/Spice86/ViewModels/VideoCardViewModel.cs, src/Spice86/ViewModels/ViewModelWithErrorDialog.cs, src/Spice86/Views/BreakpointsView.axaml, src/Spice86/Views/BreakpointsView.axaml.cs, src/Spice86/Views/DisassemblyView.axaml, src/Spice86/Views/DisassemblyView.axaml.cs, src/Spice86/Views/MemoryView.axaml, tests/Directory.Packages.props
Second round of keyboard shortcuts, and of breakpoints support.
=> Feat/debugger QoL part two

src/Directory.Packages.props, src/Spice86/MemoryWrappers/MemoryReadOnlyBitRangeUnion.cs, tests/Directory.Packages.props
This upgrades all Nuget to their latest versions.
=> chore: Upgrade nuget packages

src/Spice86/ViewModels/DisassemblyViewModel.cs
Step Over now takes the cuurent (CS:IP) instruction to work with rather than the currently selected one.
It also now actually only steps over instructions that return.
The F10 Step Over functionality was inconsistent and tried to step over jumps and branches
Run game. Pause. Go to Disassembly view. Press F10 until you reach a call or int instruction. Press F10 again to see you end up on the instruction after the call or int.
=> fix Step Over debugger functionality.

README.md
Create a “Seer” section and show how to add an appropriate config file, saving time.
No code changes.
=> Add Seer tips to README.md

src/Directory.Packages.props, src/Spice86.MicroBenchmarkTemplate/GlobalUsings.cs, src/Spice86.MicroBenchmarkTemplate/Program.cs, src/Spice86.MicroBenchmarkTemplate/Spice86.MicroBenchmarkTemplate.csproj, src/Spice86.sln
An optional micro-benchmark project for usage if anyone wants to.
=> code microbenchmark template

src/Spice86/ViewModels/CpuViewModel.cs, src/Spice86/ViewModels/MainWindowViewModel.cs, src/Spice86/ViewModels/MidiViewModel.cs, src/Spice86/ViewModels/PaletteViewModel.cs, src/Spice86/ViewModels/SoftwareMixerViewModel.cs, src/Spice86/ViewModels/VideoCardViewModel.cs, src/Spice86/Views/CpuView.axaml.cs, src/Spice86/Views/MidiView.axaml.cs, src/Spice86/Views/PaletteView.axaml.cs, src/Spice86/Views/SoftwareMixerView.axaml.cs, src/Spice86/Views/VideoCardView.axaml.cs
Also the PaletteViewModel has a cache, and only update the displayed Color if it is different.
=> fix: No ViewModel update if we only show MainWindow

src/Spice86/Infrastructure/DispatcherTimerStarter.cs, src/Spice86/ViewModels/CpuViewModel.cs, src/Spice86/ViewModels/IEmulatorObjectViewModel.cs, src/Spice86/ViewModels/MidiViewModel.cs, src/Spice86/ViewModels/PaletteViewModel.cs, src/Spice86/ViewModels/SoftwareMixerViewModel.cs, src/Spice86/ViewModels/VideoCardViewModel.cs, src/Spice86/Views/CpuView.axaml.cs, src/Spice86/Views/MidiView.axaml.cs, src/Spice86/Views/PaletteView.axaml.cs, src/Spice86/Views/SoftwareMixerView.axaml.cs, src/Spice86/Views/VideoCardView.axaml.cs
This makes performance a little bit better.
=> fix: Completely stop view update timers on visual tree detach

src/Spice86.Core/Emulator/OperatingSystem/DosFileManager.cs
=> fix: allow for opening a host file by DOS more than once

src/Spice86.Core/Emulator/InterruptHandlers/Input/Keyboard/KeyboardInt16Handler.cs
This PR avoid busy-waiting for keyboard events and solves #1290. CfgCpu chokes on it.
Busy waiting is the wrong thing to do while waiting for Keystrokes, though we have to block the instruction. The best way to solve it IMHO is to set a flag that signals "please stay at the current instruction, process interrupts, dma etc. and come back".
The benefit is that the code is much more responsive and reacts immediately to keystrokes while also consuming much less CPU resources with CfgCpu.
I was not able to implement the same hack in the old CPU, therefore I added a compatibility mode where it would still use the busy wait with the old CPU.
It is a bit hacky but it works :)
DosBox does it similarly.
Run the game, select a language.
=> fix: cadaver CfgCpu hanging

src/Directory.Packages.props, tests/Directory.Packages.props
Tested the UI to see any issues - I encountered none.
Dune and Krondor still start up (because the UI still works).
=> chore: update nugets

src/Spice86.Core/Emulator/CPU/CfgCpu/ParsedInstruction/Instructions/Aad.cs, src/Spice86.Core/Emulator/CPU/InstructionsImpl/Instructions8.cs
Fixes IF going to 0 due to bad AAD implementation
Fixes floppy dune.
=> AAD was clearing all the flags.

src/Spice86.Core/Emulator/OperatingSystem/DosFileManager.cs
PYRO2 opens a file and re-creates it again.
Ensure we close it if it was opened first, in order to avoid an exception.
Closes #1364 
Fixes a crash that should not happen.
Already tested with the game reported in the issue. The game runs.
=> fix: an open file could not be re-created without closing (PYRO2)
